# Generated by Django 5.0.3 on 2024-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
